[package]
name = "sos-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", default-features = false, features = ["derive"] }
postcard = "1"
heapless = { version = "0.7", features = ["serde"] }
critical-section = "1.1"
embedded-hal = "1"
subtle = { version = "2", default-features = false }

[features]
std = ["critical-section/std"]