    [package]
name = "sos-core-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.sos-core]
path = ".."

[[bin]]
name = "from_frame"
path = "fuzz_targets/from_frame.rs"
test = false
doc = false
bench = false
